/**
 * NOTE: When adding a new country also add to netlify/edge-functions/siteaccess.mts
 * Edge functions cannot import project files
 * Both lists will need to be maintained separately
 */
const klarnaIds = {
  dataClientIds: {
    EU: '9c8a7017-ad57-55df-836d-614e67e412ee',
    NA: '73f3022f-53d7-564a-b876-09be2a1f63af',
    AU: '701243cb-b680-5e01-ae1e-860e6f262912',
  },
  regionIds: {
    EU: 'klarna-eu',
    AU: 'klarna-au',
    NA: 'klarna-na',
  },
};

const countries = [
  {
    label: 'Austria',
    locale: 'en-AT',
    currency: 'EUR',
    domain: 'vuoriclothing.at',
    checkoutDomain: 'checkout.vuoriclothing.at',
    cookieDomain: 'vuoriclothing.at',
    headlessCheckoutReturnDomain: 'vuoriclothing.at',
    coordinates: { lat: 47.5162, lng: 14.5501 },
    countryCode: 'AT',
    language: 'en',
    boldMetricsEnabled: true,
    defaultEmailSubscription: false,
    displayAfterpay: false,
    displayKlarna: true,
    klarnaId: klarnaIds.regionIds.EU,
    klarnaDataClientId: klarnaIds.dataClientIds.EU,
    isInternational: true,
    isNewIntlCountry: true,
    lengthUnit: 'cm',
  },
  {
    label: 'Australia',
    locale: 'en-AU',
    currency: 'AUD',
    domain: 'vuoriclothing.com.au',
    checkoutDomain: 'checkout.vuoriclothing.com.au',
    cookieDomain: 'vuoriclothing.com.au',
    headlessCheckoutReturnDomain: 'vuoriclothing.com.au',
    coordinates: { lat: -25.274398, lng: 133.775136 },
    countryCode: 'AU',
    language: 'en',
    boldMetricsEnabled: false,
    defaultEmailSubscription: false,
    displayAfterpay: false,
    displayKlarna: true,
    klarnaId: klarnaIds.regionIds.AU,
    klarnaDataClientId: klarnaIds.dataClientIds.AU,
    isInternational: true,
    lengthUnit: 'cm',
  },
  {
    label: 'Belgium',
    locale: 'en-BE',
    currency: 'EUR',
    domain: 'vuoriclothing.be',
    checkoutDomain: 'checkout.vuoriclothing.be',
    cookieDomain: 'vuoriclothing.be',
    headlessCheckoutReturnDomain: 'vuoriclothing.be',
    coordinates: { lat: 50.5039, lng: 4.4699 },
    countryCode: 'BE',
    language: 'en',
    boldMetricsEnabled: true,
    defaultEmailSubscription: false,
    displayAfterpay: false,
    displayKlarna: true,
    klarnaId: klarnaIds.regionIds.EU,
    klarnaDataClientId: klarnaIds.dataClientIds.EU,
    isInternational: true,
    isNewIntlCountry: true,
    lengthUnit: 'cm',
  },
  {
    label: 'Canada',
    locale: 'en-CA',
    currency: 'CAD',
    domain: 'vuoriclothing.ca',
    checkoutDomain: 'checkout.vuoriclothing.ca',
    cookieDomain: 'vuoriclothing.ca',
    headlessCheckoutReturnDomain: 'vuoriclothing.ca',
    coordinates: { lat: 56.130366, lng: -106.346771 },
    countryCode: 'CA',
    language: 'en',
    boldMetricsEnabled: true,
    defaultEmailSubscription: false,
    displayAfterpay: false,
    displayKlarna: true,
    klarnaId: klarnaIds.regionIds.NA,
    klarnaDataClientId: klarnaIds.dataClientIds.NA,
    isInternational: true,
    lengthUnit: 'cm',
  },
  {
    label: 'Denmark',
    locale: 'en-DK',
    currency: 'DKK',
    domain: 'vuoriclothing.dk',
    checkoutDomain: 'checkout.vuoriclothing.dk',
    cookieDomain: 'vuoriclothing.dk',
    headlessCheckoutReturnDomain: 'vuoriclothing.dk',
    coordinates: { lat: 56.2639, lng: 9.5018 },
    countryCode: 'DK',
    language: 'en',
    boldMetricsEnabled: true,
    defaultEmailSubscription: false,
    displayAfterpay: false,
    displayKlarna: true,
    klarnaId: klarnaIds.regionIds.EU,
    klarnaDataClientId: klarnaIds.dataClientIds.EU,
    isInternational: true,
    isNewIntlCountry: true,
    lengthUnit: 'cm',
  },
  {
    label: 'Finland',
    locale: 'en-FI',
    currency: 'EUR',
    domain: 'vuoriclothing.fi',
    checkoutDomain: 'checkout.vuoriclothing.fi',
    cookieDomain: 'vuoriclothing.fi',
    headlessCheckoutReturnDomain: 'vuoriclothing.fi',
    coordinates: { lat: 61.9241, lng: 25.7482 },
    countryCode: 'FI',
    language: 'en',
    boldMetricsEnabled: true,
    defaultEmailSubscription: false,
    displayAfterpay: false,
    displayKlarna: true,
    klarnaId: klarnaIds.regionIds.EU,
    klarnaDataClientId: klarnaIds.dataClientIds.EU,
    isInternational: true,
    isNewIntlCountry: true,
    lengthUnit: 'cm',
  },
  {
    label: 'France',
    locale: 'fr-FR',
    currency: 'EUR',
    domain: 'vuoriclothing.fr',
    checkoutDomain: 'checkout.vuoriclothing.fr',
    cookieDomain: 'vuoriclothing.fr',
    headlessCheckoutReturnDomain: 'vuoriclothing.fr',
    coordinates: { lat: 46.227638, lng: 2.213749 },
    countryCode: 'FR',
    language: 'fr',
    boldMetricsEnabled: true,
    defaultEmailSubscription: false,
    displayAfterpay: false,
    displayKlarna: true,
    klarnaId: klarnaIds.regionIds.EU,
    klarnaDataClientId: klarnaIds.dataClientIds.EU,
    isInternational: true,
    lengthUnit: 'cm',
  },
  {
    label: 'Germany',
    locale: 'de-DE',
    currency: 'EUR',
    domain: 'vuoriclothing.de',
    checkoutDomain: 'checkout.vuoriclothing.de',
    cookieDomain: 'vuoriclothing.de',
    headlessCheckoutReturnDomain: 'vuoriclothing.de',
    coordinates: { lat: 51.165691, lng: 10.451526 },
    countryCode: 'DE',
    language: 'de',
    boldMetricsEnabled: true,
    defaultEmailSubscription: false,
    displayAfterpay: false,
    displayKlarna: true,
    klarnaId: klarnaIds.regionIds.EU,
    klarnaDataClientId: klarnaIds.dataClientIds.EU,
    isInternational: true,
    lengthUnit: 'cm',
  },
  {
    label: 'Hong Kong (SAR)',
    shopifyCountry: 'Hong Kong',
    locale: 'zh-HK',
    currency: 'HKD',
    domain: 'vuoriclothing.hk',
    checkoutDomain: 'checkout.vuoriclothing.hk',
    cookieDomain: 'vuoriclothing.hk',
    headlessCheckoutReturnDomain: 'vuoriclothing.hk',
    coordinates: { lat: 22.3193039, lng: 114.1693611 },
    countryCode: 'HK',
    language: 'zh',
    boldMetricsEnabled: false,
    defaultEmailSubscription: false,
    displayAfterpay: false,
    displayKlarna: false,
    isInternational: true,
    lengthUnit: 'cm',
  },
  {
    label: 'Ireland (Republic of)',
    shopifyCountry: 'Ireland',
    locale: 'en-IE',
    currency: 'EUR',
    domain: 'ie.vuoriclothing.com',
    checkoutDomain: 'checkout.ie.vuoriclothing.com',
    cookieDomain: 'ie.vuoriclothing.com',
    headlessCheckoutReturnDomain: 'ie.vuoriclothing.com',
    coordinates: { lat: 53.41291, lng: -8.24389 },
    countryCode: 'IE',
    language: 'en',
    boldMetricsEnabled: true,
    defaultEmailSubscription: false,
    displayAfterpay: false,
    displayKlarna: false,
    isInternational: true,
    lengthUnit: 'cm',
  },
  {
    label: 'Italy',
    locale: 'en-IT',
    currency: 'EUR',
    domain: 'vuoriclothing.it',
    checkoutDomain: 'checkout.vuoriclothing.it',
    cookieDomain: 'vuoriclothing.it',
    headlessCheckoutReturnDomain: 'vuoriclothing.it',
    coordinates: { lat: 41.8719, lng: 12.5674 },
    countryCode: 'IT',
    language: 'en',
    boldMetricsEnabled: true,
    defaultEmailSubscription: false,
    displayAfterpay: false,
    displayKlarna: true,
    klarnaId: klarnaIds.regionIds.EU,
    klarnaDataClientId: klarnaIds.dataClientIds.EU,
    isInternational: true,
    isNewIntlCountry: true,
    lengthUnit: 'cm',
  },
  {
    label: 'Japan',
    locale: 'ja-JP',
    currency: 'JPY',
    domain: 'vuoriclothing.jp',
    checkoutDomain: 'checkout.vuoriclothing.jp',
    cookieDomain: 'vuoriclothing.jp',
    headlessCheckoutReturnDomain: 'vuoriclothing.jp',
    coordinates: { lat: 36.2048, lng: 138.2529 },
    countryCode: 'JP',
    language: 'ja',
    boldMetricsEnabled: false,
    defaultEmailSubscription: false,
    displayAfterpay: false,
    displayKlarna: false,
    isInternational: true,
    isNewIntlCountry: true,
    lengthUnit: 'cm',
  },
  {
    label: 'Mexico',
    locale: 'es-MX',
    currency: 'MXN',
    domain: 'vuoriclothing.mx',
    checkoutDomain: 'checkout.vuoriclothing.mx',
    cookieDomain: 'vuoriclothing.mx',
    headlessCheckoutReturnDomain: 'vuoriclothing.mx',
    coordinates: { lat: 23.634501, lng: -102.552784 },
    countryCode: 'MX',
    language: 'es',
    boldMetricsEnabled: false,
    defaultEmailSubscription: false,
    displayAfterpay: false,
    displayKlarna: false,
    isInternational: true,
    lengthUnit: 'cm',
  },
  {
    label: 'Netherlands',
    locale: 'nl-NL',
    currency: 'EUR',
    domain: 'vuoriclothing.nl',
    checkoutDomain: 'checkout.vuoriclothing.nl',
    cookieDomain: 'vuoriclothing.nl',
    headlessCheckoutReturnDomain: 'vuoriclothing.nl',
    coordinates: { lat: 52.132633, lng: 5.291265999999999 },
    countryCode: 'NL',
    language: 'nl',
    boldMetricsEnabled: true,
    defaultEmailSubscription: false,
    displayAfterpay: false,
    displayKlarna: true,
    klarnaId: klarnaIds.regionIds.EU,
    klarnaDataClientId: klarnaIds.dataClientIds.EU,
    isInternational: true,
    lengthUnit: 'cm',
  },
  {
    label: 'Norway',
    locale: 'en-NO',
    currency: 'NOK',
    domain: 'vuoriclothing.no',
    checkoutDomain: 'checkout.vuoriclothing.no',
    cookieDomain: 'vuoriclothing.no',
    headlessCheckoutReturnDomain: 'vuoriclothing.no',
    coordinates: { lat: 60.472, lng: 8.4689 },
    countryCode: 'NO',
    language: 'en',
    boldMetricsEnabled: true,
    defaultEmailSubscription: false,
    displayAfterpay: false,
    displayKlarna: true,
    klarnaId: klarnaIds.regionIds.EU,
    klarnaDataClientId: klarnaIds.dataClientIds.EU,
    isInternational: true,
    isNewIntlCountry: true,
    lengthUnit: 'cm',
  },
  {
    label: 'Portugal',
    locale: 'pt-PT',
    currency: 'EUR',
    domain: 'vuoriclothing.pt',
    checkoutDomain: 'checkout.vuoriclothing.pt',
    cookieDomain: 'vuoriclothing.pt',
    headlessCheckoutReturnDomain: 'vuoriclothing.pt',
    coordinates: { lat: 39.3999, lng: 8.2245 },
    countryCode: 'PT',
    language: 'pt',
    boldMetricsEnabled: true,
    defaultEmailSubscription: false,
    displayAfterpay: false,
    displayKlarna: false,
    isInternational: true,
    isNewIntlCountry: true,
    lengthUnit: 'cm',
  },
  {
    label: 'Singapore',
    locale: 'zh-SG',
    currency: 'SGD',
    domain: 'vuoriclothing.sg',
    checkoutDomain: 'checkout.vuoriclothing.sg',
    cookieDomain: 'vuoriclothing.sg',
    headlessCheckoutReturnDomain: 'vuoriclothing.sg',
    coordinates: { lat: 1.352083, lng: 103.819836 },
    countryCode: 'SG',
    language: 'zh',
    boldMetricsEnabled: false,
    defaultEmailSubscription: false,
    displayAfterpay: false,
    displayKlarna: false,
    isInternational: true,
    lengthUnit: 'cm',
  },
  {
    label: 'Spain',
    locale: 'es-ES',
    currency: 'EUR',
    domain: 'vuoriclothing.es',
    checkoutDomain: 'checkout.vuoriclothing.es',
    cookieDomain: 'vuoriclothing.es',
    headlessCheckoutReturnDomain: 'vuoriclothing.es',
    coordinates: { lat: 40.4637, lng: 3.7492 },
    countryCode: 'ES',
    language: 'es',
    boldMetricsEnabled: true,
    defaultEmailSubscription: false,
    displayAfterpay: false,
    displayKlarna: true,
    klarnaId: klarnaIds.regionIds.EU,
    klarnaDataClientId: klarnaIds.dataClientIds.EU,
    isInternational: true,
    isNewIntlCountry: true,
    lengthUnit: 'cm',
  },
  {
    label: 'Sweden',
    locale: 'en-SE',
    currency: 'SEK',
    domain: 'vuoriclothing.se',
    checkoutDomain: 'checkout.vuoriclothing.se',
    cookieDomain: 'vuoriclothing.se',
    headlessCheckoutReturnDomain: 'vuoriclothing.se',
    coordinates: { lat: 60.1282, lng: 18.6435 },
    countryCode: 'SE',
    language: 'en',
    boldMetricsEnabled: true,
    defaultEmailSubscription: false,
    displayAfterpay: false,
    displayKlarna: true,
    klarnaId: klarnaIds.regionIds.EU,
    klarnaDataClientId: klarnaIds.dataClientIds.EU,
    isInternational: true,
    isNewIntlCountry: true,
    lengthUnit: 'cm',
  },
  {
    label: 'Switzerland',
    locale: 'en-CH',
    currency: 'CHF',
    domain: 'vuoriclothing.ch',
    checkoutDomain: 'checkout.vuoriclothing.ch',
    cookieDomain: 'vuoriclothing.ch',
    headlessCheckoutReturnDomain: 'vuoriclothing.ch',
    coordinates: { lat: 46.8182, lng: 46.8182 },
    countryCode: 'CH',
    language: 'en',
    boldMetricsEnabled: true,
    defaultEmailSubscription: false,
    displayAfterpay: false,
    displayKlarna: false,
    isInternational: true,
    isNewIntlCountry: true,
    lengthUnit: 'cm',
  },
  {
    label: 'United Arab Emirates',
    locale: 'ar-AE',
    currency: 'AED',
    domain: 'vuoriclothing.ae',
    checkoutDomain: 'checkout.vuoriclothing.ae',
    cookieDomain: 'vuoriclothing.ae',
    headlessCheckoutReturnDomain: 'vuoriclothing.ae',
    coordinates: { lat: 23.424076, lng: 53.847818 },
    countryCode: 'AE',
    language: 'ar',
    boldMetricsEnabled: false,
    defaultEmailSubscription: false,
    displayAfterpay: false,
    displayKlarna: false,
    isInternational: true,
    lengthUnit: 'cm',
  },
  {
    label: 'United Kingdom',
    locale: 'en-GB',
    currency: 'GBP',
    domain: 'vuoriclothing.co.uk',
    checkoutDomain: 'checkout.vuoriclothing.co.uk',
    cookieDomain: 'vuoriclothing.co.uk',
    headlessCheckoutReturnDomain: 'vuoriclothing.co.uk',
    coordinates: { lat: 55.378051, lng: -3.435973 },
    countryCode: 'GB',
    language: 'en',
    boldMetricsEnabled: true,
    defaultEmailSubscription: false,
    displayAfterpay: false,
    displayKlarna: true,
    klarnaId: klarnaIds.regionIds.EU,
    klarnaDataClientId: klarnaIds.dataClientIds.EU,
    isInternational: true,
    lengthUnit: 'cm',
  },
  {
    label: 'United States',
    locale: 'en-US',
    currency: 'USD',
    domain: 'vuoriclothing.com',
    checkoutDomain: 'checkout.vuoriclothing.com',
    cookieDomain: 'vuoriclothing.com',
    headlessCheckoutReturnDomain: 'vuoriclothing.com',
    coordinates: { lat: 44.967243, lng: -96.771556 },
    defaultZoom: 4,
    countryCode: 'US',
    language: 'en',
    boldMetricsEnabled: true,
    defaultEmailSubscription: true,
    displayAfterpay: true,
    displayKlarna: false,
    isInternational: false,
    lengthUnit: 'in',
    supportPhoneNumber: '+1-844-880-5355',
  },
];

module.exports.countries = countries;

module.exports.generateTestCountries = function generateTestCountries() {
  if (process.env.CONTEXT === 'deploy-preview' && process.env.DEPLOY_PRIME_URL) {
    const previewSub = process.env.DEPLOY_PRIME_URL.split('.')[0].replace('https://', '');

    return countries.map(country => ({
      ...country,
      domain: `${previewSub}.web.${country.domain}`,
      checkoutDomain: `sandbox.checkout.${country.checkoutDomain.replace('checkout.', '')}`,
      headlessCheckoutReturnDomain: `${previewSub}.web.${country.headlessCheckoutReturnDomain}`,
    }));
  }

  if (process.env.BRANCH === 'development') {
    return countries.map(country => ({
      ...country,
      domain: `development.web.${country.domain}`,
      checkoutDomain: `development.checkout.${country.checkoutDomain.replace('checkout.', '')}`,
      headlessCheckoutReturnDomain: `development.web.${country.headlessCheckoutReturnDomain}`,
    }));
  }

  if (process.env.BRANCH === 'sandbox') {
    return countries.map(country => ({
      ...country,
      domain: `sandbox.web.${country.domain}`,
      checkoutDomain: `sandbox.checkout.${country.checkoutDomain.replace('checkout.', '')}`,
      headlessCheckoutReturnDomain: `sandbox.web.${country.headlessCheckoutReturnDomain}`,
    }));
  }

  if (process.env.BRANCH === 'staging') {
    return countries.map(country => ({
      ...country,
      domain: `staging.web.${country.domain}`,
      checkoutDomain: `staging.checkout.${country.checkoutDomain.replace('checkout.', '')}`,
      headlessCheckoutReturnDomain: `staging.web.${country.headlessCheckoutReturnDomain}`,
    }));
  }

  return countries.map(country => ({
    ...country,
    domain: country.domain,
    checkoutDomain: country.checkoutDomain,
    headlessCheckoutReturnDomain: country.headlessCheckoutReturnDomain,
  }));
};
